# Generated by Django 4.1.5 on 2023-09-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Listing',
            new_name='listing',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=5000),
        ),
    ]
